# Generated by Django 2.2.12 on 2020-09-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200921_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pictures',
            field=models.ImageField(upload_to='pictures', verbose_name='图片'),
        ),
    ]
