# Generated by Django 2.2.12 on 2020-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200917_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', height_field=250, upload_to='avatar', verbose_name='头像', width_field=250),
        ),
    ]
